version: '3'

services:
  nginx:
    image: whai_blog_nginx:v1.0
    build:
      context: .
      dockerfile: ./Nginx/Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/log:/var/log/nginx
      - ./Nginx/conf.d/:/etc/nginx/conf.d/
      - ./Nginx/html:/usr/share/nginx/html
    depends_on:
      - whaiblog01
      - whaiblog02
  # 声明在同一个docker-compose.yml中的服务，不需要新建网络，他们便可以通过服务名（redis,mysql）互相通信
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mysql:
    image: whai_blog_mysql:v1.0
    command: --lower_case_table_names=1
    build:
      context: .
      dockerfile: ./Mysql/Dockerfile-mysql
#    restart: unless-stopped
 #   environment:
   #   - MYSQL_ROOT_PASSWORD=1263758923Mysql@
  #    - MYSQL_DATABASE=blog
    ports:
      - "3307:3306"
    volumes:
      - ./Mysql:/var/lib/mysql
#    networks:
#      my_network:
#        aliases:
#          - myMysql
#          aliases ：同一网络上的其他容器可以使用服务名称或此别名来连接到对应容器的服务。
  whaiblog01:
    image: whai_blog_server:v1.0
    build:
      context: .
      dockerfile: ./Springboot/Dockerfile-springboot
    ports:
      - "12139:8111"
    volumes:
      - ./Springboot/logs:/logs
      - ./Springboot/img:/img
      - ./Springboot/file:/file
    links:
      - redis
      - mysql
    depends_on:
      - redis
      - mysql
  whaiblog02:
    image: whai_blog_server:v1.0
    build:
      context: .
      dockerfile: ./Springboot/Dockerfile-springboot
    ports:
      - "12140:8111"
    volumes:
      - ./Springboot/logs:/logs
      - ./Springboot/img:/img
      - ./Springboot/file:/file
    links:
      - redis
      - mysql
    depends_on:
      - redis
      - mysql

#    networks:
#      - my_network
#networks:
#  my_network:
#    driver: bridge


